import { NextRequest, NextResponse } from "next/server";
import { nftCollectionContractAddress } from "../../../../utils/contract";

import { metadata } from "@/app/layout";

// Counter variable to keep track of minted NFTs
let nftCounter = 0;

const {
    ENGINE_URL,
    THIRDWEB_SECRET_KEY,
    BACKEND_WALLET_ADDRESS,
} = process.env;

export async function POST(req: Request) {
    if (
        !ENGINE_URL ||
        !THIRDWEB_SECRET_KEY ||
        !BACKEND_WALLET_ADDRESS
    ) {
        throw new Error("Missing environment variable");
    }

    const { nftImage, address, prompt, name } = await req.json();

    nftCounter += 1; // Increment the counter
    const nftName = name || `AI NFT #${nftCounter}`;
    const nftDescription = prompt || "An NFT generated by AI";

    const res = await fetch(
        `${ENGINE_URL}/contract/sepolia/${nftCollectionContractAddress}/erc721/mint-to`, {
            method: "POST",
            headers: {
                "Authorization": `Bearer ${THIRDWEB_SECRET_KEY}`,
                "Content-Type": "application/json",
                "x-backend-wallet-address": BACKEND_WALLET_ADDRESS,
            },
            body: JSON.stringify({
                receiver: address,
                metadata: {
                    name: nftName,
                    description: nftDescription,
                    image: nftImage,
                }
            })
        }
    );

    if (res.ok) {
        console.log("Minted NFT", await res.json());
    } else {
        console.log("Failed to mint NFT", await res.text());
    }

    return NextResponse.json({ message: "Successfully minted NFT" });
}
